[package]
name = "server"
version = "0.1.0"
authors = ["Zac Vuković <contact@cyn1x.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rs-handler" = { path = "../../lib/rs-handler" }
"rs-network" = { path = "../../lib/rs-network" }
"rs-game" = { path = "../rs-game" }
